# Generated by Django 5.1.4 on 2024-12-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesiteuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
