# Generated by Django 5.1.4 on 2024-12-15 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_notesiteuser_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesiteuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
