# Generated by Django 5.1.4 on 2024-12-22 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notesiteuser_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesiteuser',
            name='follows',
        ),
        migrations.AlterField(
            model_name='notesiteuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notesiteuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
