# Generated by Django 5.1.4 on 2024-12-26 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_notesiteuser_follows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_ips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
