# Generated by Django 5.1.4 on 2025-01-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_loginip'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesiteuser',
            name='is_key_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notesiteuser',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
