# Generated by Django 5.1.4 on 2025-01-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_notesiteuser_is_key_enabled_notesiteuser_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesiteuser',
            name='otp_secret',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
