version: '3.9'

services:
  web:
    build: .
    command: bash -c  "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 notes_keeping_site.wsgi:application" 
    volumes:
      - .:/app
    ports:
      - "8000:8000"   
    networks:
      - backend
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./staticfiles:/app/staticfiles
      - ./nginx/certs:/etc/nginx/certs  
    ports:
      - "80:80"                    
      - "443:443"                  
    networks:
      - backend
    restart: always  
    depends_on:
      - web

volumes:
  postgres_data:  

networks:
  backend:
